repos:
  - repo: local
    hooks:
      - id: strip-image-metadata
        name: Strip EXIF metadata from staged images
        entry: ./scripts/hooks/pre-commit
        language: system
        types: [image]
