repos:
  - repo: local
    hooks:
      - id: strip-image-metadata
        name: Strip EXIF metadata from staged images
        entry: bash scripts/hooks/pre-commit
        language: script
        types: [image]
